version: '3'
services:
  react_app:
    build: .
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./:/usr/src/react_app
    command: sh -c 'cd react_app && yarn start'
    ports:
      - '4000:4000'
    tty: true